jobs:
  create-patient:
    expression: >
      post('Patient', {
        body: dataValue('$'),
        headers: {
          'Content-Type': 'application/json',
          Authorization: 'Custom test',
          'If-None-Exist': state =>
            `identifier=${dataValue('identifier[0].value')(state)}`,
        },
      });
    adaptor: '@openfn/language-http'
    trigger: patient-message
    credential: openhim

  create-organization:
    expression: >
      post('Organization', {
        body: dataValue('$'),
        headers: {
          'Content-Type': 'application/json',
          Authorization: 'Custom test',
          'If-None-Exist': state =>
            `identifier=${dataValue('identifier[0].value')(state)}`,
        },
      });
    adaptor: '@openfn/language-http'
    trigger: organization-message
    credential: openhim

triggers:
  patient-message:
    criteria: '{"resourceType":"Patient"}'
  organization-message:
    criteria: '{"resourceType":"Organization"}'

credentials:
  openhim:
    baseUrl: "http://10.0.0.25:5001/fhir/"