version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  lightning_cli_test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run: npm install -g @openfn/cli

      # TODO: add credentials via env
      # - run: openfn -ia ./lightning/workflow.json

  # microservice_test:
  #   machine:
  #     image: ubuntu-2004:202101-01

  #   steps:
  #     - checkout

  #     - run: npm install -g yarn

  #     - run: yarn
  #     - run: yarn setup
  #     - run: yarn test

# Orchestrate our job run sequence
workflows:
  tests:
    jobs:
      - lightning_cli_test
      # TODO: if we plan to bring back support for microservice...
      # - microservice_test
